# Generated by Django 3.1.7 on 2022-03-16 12:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0004_auto_20220226_1335'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='identity',
            new_name='userId',
        ),
    ]
