# Generated by Django 3.1.7 on 2022-03-18 11:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0005_auto_20220316_1454'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='display_photo',
        ),
    ]
